# Generated by Django 3.2 on 2021-12-14 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_slug', models.SlugField(unique=True)),
                ('auction_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('auction_end_date', models.DateTimeField()),
                ('auction_name', models.CharField(max_length=250)),
                ('starting_price', models.FloatField(default=0)),
                ('minimum_increment', models.FloatField(default=1)),
                ('has_buy_now', models.BooleanField(default=False)),
                ('buy_now_price', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('P', 'Preparation'), ('A', 'Active'), ('F', 'Finished')], default='P', max_length=3)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_auction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
